spring.application.name=storage-node
heartbeat.master-url=http://localhost:8080/heartbeat
# Leave empty for relative paths in current working directory.
# Example for WSL absolute path: /mnt/d/projects/final
storage.base-dir=/mnt/d/projects/final